# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - cmd: fuser -k 8080/tcp
        ignore_error: true
      - go run main.go
    sources:
      - "*.go"
    silent: true
